# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohnish Dubey
title: |
    Researcher at Smart Data Analytics, University of Bonn, Germany
    Dialogue Engineer at Fraunhofer IAIS, Dresden, Germany
email: dubey.mohnish5@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: MohnishDubey
github_username:  mohnish.rygbee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mohnishdubey5
linkedin_username: mohnish-dubey-bonn
#google_scholar: https://scholar.google.de/citations?user=rq9BsgcAAAAJ&hl=en
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.de/citations?user=rq9BsgcAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
                Hi, my name is Mohnish Dubey, and I am a Researcher at Smart Data Analytics and Dialogue Engineer at Fraunhofer IAIS. 

                I recently defended my PhD Thesis, and soon I will get my official doctor's degree. I have worked in the research area of Question Answering over Knowledge Graphs, Entity Linking, Relation Linking, Large Dataset Generation, Answer Representation. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AskNowNQS - Translating natural langauge question to formal query using an intermediate state.
        link: source code https://github.com/AskNowQA/AskNowNQS
        description: | # this will include new lines to allow paragraphs
          Lead to the development of question answering system over DBpedia. Here Natural language questions are normalized into an intermediary canonical syntactic form and then translated into a SPARQL
      
      - layout: top-middle
        title: LC-QuAD- Generating Large scale dataset for Question Answering over Knowledge Graph.
        link: http://lc-quad.sda.tech
        description: | # this will include new lines to allow paragraphs
          LC-QuAD: Lead the project with aim to create a Question Answering data set with the pair of Natural Language question to their corresponding SPARQL query. LC-QuAD 1.0 published a dataset of 5,000 question over DBpedia. LC-QuAD 2.0 published a dataset of 30,000 question over Wikidata.
      
      - layout: top-middle
        title: EARL- Joint task of Entity and Relation Linking.
        link: https://github.com/AskNowQA/EARL
        description: | # this will include new lines to allow paragraphs
          Here we developed the component to performs entity linking and relation linking as a joint single task
      
      - layout: top-middle
        title: Question Answering over Video Annotation
        link: http://lc-quad.sda.tech
        description: | # this will include new lines to allow paragraphs
          In this internal Fraunhofer project we developed a template based question answering system over ARD Video annotations, to fetch videos based on user’s input in German language.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fraunhofer IAIS , Sankt Augustin / Dresden
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Dialogue Engineer 
        caption: October 2017 - Present
        description: 
            - layout: top-middle
              title: AskNowNQS - Translating natural langauge question to formal query using an intermediate state.
              link: source code https://github.com/AskNowQA/AskNowNQS
              description: | # this will include new lines to allow paragraphs
                Lead to the development of question answering system over DBpedia. Here Natural language questions are normalized into an intermediary canonical syntactic form and then translated into a SPARQL
                
            - layout: top-middle
              title: LC-QuAD- Generating Large scale dataset for Question Answering over Knowledge Graph.
              link: http://lc-quad.sda.tech
              description: | # this will include new lines to allow paragraphs
                 LC-QuAD: Lead the project with aim to create a Question Answering data set with the pair of Natural Language question to their corresponding SPARQL query. LC-QuAD 1.0 published a dataset of 5,000 question over DBpedia. LC-QuAD 2.0 published a dataset of 30,000 question over Wikidata.
      
            - layout: top-middle
              title: EARL- Joint task of Entity and Relation Linking.
              link: https://github.com/AskNowQA/EARL
              description: | # this will include new lines to allow paragraphs
                Here we developed the component to performs entity linking and relation linking as a joint single task
      
            - layout: top-middle
              title: Question Answering over Video Annotation
              link: http://lc-quad.sda.tech
              description: | # this will include new lines to allow paragraphs
                In this internal Fraunhofer project we developed a template based question answering system over ARD Video annotations, to fetch videos based on user’s input in German language.

            
      - layout: left
        title: Smart Data Analytics, University of Bonn
        link: sda.tech
        # link_text: boringcompany.com
        sub_title: Researcher and PhD Student
        caption: January 2016 - Present
        description: | # this will include new lines to allow paragraphs
            Working on Semantic Question Answering over Knowledge Graph
      
      - layout: left
        title: AKSW, University of Liepzig
        link: sda.tech
        # link_text: boringcompany.com
        sub_title: Researcher
        caption: June 2015 - December 2015
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
