# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohnish Dubey
title: >
    Senior Researcher at Smart Data Analytics, and
    Project Leader at InfAI Dresden, Germany.
email: dubey.mohnish5@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: MohnishDubey
github_username:  mohnish.rygbee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mohnishdubey5
linkedin_username: dubeymohnish5
#google_scholar: https://scholar.google.de/citations?user=rq9BsgcAAAAJ&hl=en
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.de/citations?user=rq9BsgcAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
                Hi, my name is Mohnish Dubey, and I am a Senior Researcher at Smart Data Analytics and InfAI. Currently, I am leading the e-VITA project at InfAI, working towards designing knowledege graph based dailogue system to support active and healthy ageing. 

                Previously, I have worked as a Dialogue Engineer at Fraunhofer IAIS for more than three years. In 2021, I compeleted my PhD from University of Bonn, Germany. 
                I have worked in the research area of Question Answering over Knowledge Graphs, Dialogue Systems, Entity Linking, Relation Linking, Large Dataset Generation, Answer Representation, and general NLP and KG tasks.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AskNowNQS For Question Answering over Knowledge Graph
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Dialogue Engineer 
        caption: July 2015 - July 2016
        description: | # this will include new lines to allow paragraphs
          - Lead to the development of question answering system over DBpedia. 
          - Here Natural language questions are normalized into an intermediary canonical syntactic form and then translated into a SPARQL
          - A rule based system for question answering over DBpedia Knowledge Graph
          - source code [https://github.com/AskNowQA/AskNowNQS](https://github.com/AskNowQA/AskNowNQS)
      
      - layout: left
        title: LC-QuAD- Large scale Complex Question Answering Dataset.
        caption: March 2017 - present
        description: | # this will include new lines to allow paragraphs
          - Lead the project with aim to create a Question Answering data set with the pair of Natural Language question to their corresponding SPARQL query. 
          - LC-QuAD 1.0 published a dataset of 5,000 question over DBpedia. 
          - LC-QuAD 2.0 published a dataset of 30,000 question over Wikidata.
          - project website: [http://lc-quad.sda.tech](http://lc-quad.sda.tech)
      
      - layout: left
        title: EARL - Entity and Relation Linking for KGQA
        caption: September 2017 - December 2018
        description: | # this will include new lines to allow paragraphs
          - Developed the component to performs entity linking and relation linking as a joint single task. 
          - First by modeling the problem to Generalised Travelling Salesman Problem. 
          - Second using machine learning in order to exploit the connection density between nodes in the knowledge graph.
          - Source code: [https://github.com/AskNowQA/EARL](https://github.com/AskNowQA/EARL)
      
      - layout: left
        title: Question Answering over Video Annotation
        caption: January 2018 - June 2018
        description: | # this will include new lines to allow paragraphs
          - In this internal Fraunhofer project we developed a template based question answering system 
          - We targeted ARD Video annotations, and fetch videos based on user’s input in German language.
          
      - layout: left
        title: VANiLLa - A dataset for better Answer Representation 
        caption: January 2020 - December 2020
        description: | # this will include new lines to allow paragraphs
          - A large scale dataset for answer verbaliser for simple natural questions. 
          - The answer in this dataset are syntactically and semantically closer to the question than to the KG triple.
          - Website [https://sda.tech/projects/vanilla/](https://sda.tech/projects/vanilla/)
          


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:


      - layout: left
        title: InfAI Dresden
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Project Leader in e-VITA project
        link: https://www.e-vita.coach
        caption: May 2021 - Ongoing
        description: | # this will include new lines to allow paragraphs
            - Developing use-cases and user stories for the dialogue system with the vision of the project of active healthy ageing
            - Investigating several components(such as translation services) and pipelines to use them to meet the project requirements
            - Developing a Dialogue system with RASA framework and further integrating Question Answering capabilities.


      - layout: left
        title: Smart Data Analytics, University of Bonn
        link: https://www.sda.tech
        # link_text: boringcompany.com
        sub_title: Senoior Researcher
        caption: January 2016 - Present
        description: | # this will include new lines to allow paragraphs
            - Defended Ph.D. Thesis on Question Answering over Knowledge Graph (KGQA). (January 2021)
            - Published state of the art systems on KGQA, Entity and Relation Linking and Dataset generation.
            - Managed and supervised student assistants for KGQA project, AskNow. 
            - Conducted research on Answer Representation and managed UI development for KGQA.
            - Conducted NLP Labs and Seminars, currently also mentoring master student projects


      - layout: left
        title: Fraunhofer IAIS , Sankt Augustin / Dresden
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Dialogue Engineer 
        caption: October 2017 - May 2021
        description: | # this will include new lines to allow paragraphs
            - Worked on Semantic Question Answering over Knowledge Graph.
            - Lead developer in projects on Question Answering over Video Annotations in German language.
            - Supported with evaluation on Dialogue System for Car Infotainment. 
            - Generated Question Answering benchmarking for Conversation AI systems in specific domains such as COVID-19 data, and Financial reports.

            

      
      - layout: left
        title: AKSW, University of Liepzig
        link: https://www.aksw.org
        # link_text: boringcompany.com
        sub_title: Guest Researcher
        caption: June 2015 - December 2015
        description: | # this will include new lines to allow paragraphs
            - In the six month internship worked and gained knowledge in the field of Semantic Web and Question Answering. 
            - Learned about Knowledge gGraphs and SPARQL Query.
            - Worked on rule based translation of English Questions to SPARQL query.

  - title: Research Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      - PNEL: Pointer Network based End-To-End Entity Linking over Knowledge Graphs, Debayan Banerjee, Debanjan Chaudhuri, Mohnish Dubey and Jens Lehmann, in Proceedings of International Semantic Web Conference 2020 
      - IQA: Interactive query construction in semantic question answering systems, By Hamid Zafar, Mohnish Dubey, Jens Lehmann, Elena Demidova, in Journal of Web Semantics.
      - LC-QuAD 2.0: A large dataset for complex question answering over Wikidata and DBpedia By Mohnish Dubey, Debayan Banerjee, Abdelrahman Abdelkawi, Jens Lehmann in Proceedings of International Semantic Web Conference 2019, New Zealand
      - EARL: Joint Entity and Relation Linking for Question Answering over Knowledge Graphs by Mohnish Dubey, Debayan Banerjee, Debanjan Chaudhuri and Jens Lehmann in Proceedings of International Semantic Web Conference 2018
      - LC-QuAD : A Corpus for Complex Question Answering over Knowledge Graphs by Priyansh Trivedi, Gaurav Maheshwari, Mohnish Dubey and Jens Lehmanni in Proceedings of the International Semantic Web Conference 2017.
      - How to Revert Question Answering on Knowledge Graphs by Gaurav Maheshwari, Mohnish Dubey, Priyansh Trivedi and Jens Lehmann. In Proceedings of the International Semantic Web Conference 2017.
      - AskNow: A Framework for Natural Language Query Formalization in SPARQL by Mohnish Dubey, Sourish Dasgupta, Ankit Sharma, Konrad Hoffner, and Jens Lehmann in Proceedings of the Extended Semantic Web Conference 2016.
      - VANiLLa : Verbalised ANswers in Natural Language at Large scale by Debanjali Biswas, Mohnish Dubey, Md Rashad Al Hasan Rony and Jens Lehmann, under review process.
  
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Bonn
        caption: Jan 2016 - Jan 2021
        sub_title: Ph.D. in Computer Science
        description: | # this will include new lines to allow paragraphs
          During my PhD at the University of Bonn, I was a part of the Smart Data Analytics group lead by Prof. Jens Lehmann. 
          

      - layout: left
        title: DA-IICT, India
        caption: 2012 - 2014
        sub_title: Master of Technology
        description: | # this will include new lines to allow paragraphs
          At Technology Dhirubhai Ambani Institute of Information & Communication Technology,  I completed my master's degree with machine intelligence speciation. In my master thesis, I worked on the normalization of negative sentences. Here I was first introduced to Semantic Web by Dr Sourish Dasgupta.       

      - layout: left
        title: JNCT, Bhopal India
        caption: 2008 - 2012
        sub_title: Bachelor of Engineering
        description: | # this will include new lines to allow paragraphs
          I completed my Engineering degree in Computer Science at Jai Narain College of Technology affiliated to Rajiv Gandhi Proudyogiki Vishwavidyalaya, India. During my last year, I scored 98 percentile in the GATE exam, motivating me to study computer science further. 
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in research some of my other interests and hobbies are:
      - Huge fan of Cricket.
      - Photo editing and graphics.
      - Picked up intrest in Travelling during my PhD.
      - Listening music.

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
